#!/bin/ksh
# This file is part of www-log-viewer and is targeting primarly OpenBSD
# Copyright 5 Mode and other contributors; Licensed MIT

param1=$1

if [ "X$param1" != "X" ]; then
  # 'Create only file' param..
	if [ "X$param1" != "X-c" ]; then
    echo "Invalid param1 value."
    exit 1  	
	fi
fi

if [ ! -e /var/log/php_errors.log ];  then
  echo "/var/log/php_errors.log doesn't exists."
  exit 1
fi
if [ ! -e /var/log/nginx/error.log ];  then
  echo "/var/log/nginx/error.log doesn't exists."
  exit 1
fi

if [ "X$param1" != "X-c" ]; then
  echo "This file is part of www-log-viewer and is targeting primarly OpenBSD"
  echo "Copyright © 5 Mode and other contributors; Licensed MIT"
fi

# Create scripts 'extras'..
tail -n10 /var/log/php_errors.log > myphp_errors.log
tail -n10 /var/log/nginx/error.log > mynginx_errors.log

# Showing logs..
if [ "X$param1" != "X-c" ]; then
  d=`date "+%S"`
  clear; pr -F -l 20 myphp_errors.log mynginx_errors.log 
  while true; do
    if [ "X$d" = "X58" ]; then
			# Create scripts 'extras'..
			tail -n10 /var/log/php_errors.log > myphp_errors.log
			tail -n10 /var/log/nginx/error.log > mynginx_errors.log

      clear; pr -F -l 20 myphp_errors.log mynginx_errors.log 
    fi
    if [ "X$input" = "Xq" ]; then
      break
    fi    
    d=`date "+%S"`
  done
fi

exit 0